---
  - name: Install nginx
    become: true
    # become_user: someUser
    apt:  pkg=nginx state=present

  - name: Install nginx vhost for specified site
    become: true
    template:
      src: templates/default.j2
      dest: /etc/nginx/sites-enabled/default
    notify: reload nginx